config/routes.rb
Sensa::Application.routes.draw do
  resources :sensors


  post "feed" => "feeder#feed"
  post "starve" => "feeder#starve"
  post "dose" => "feeder#dose"
  post "cancel/:id" => "feeder#cancel", :as => :cancel_dose
  get "feeder" => "feeder#index"
  root to: "sensors#index"
end

app/models/dev_serial_port.rb
# Development stub for SimpleSerialPort
#
# When running in development mode, I don't necessarily have a real
# Arduino to connect via serial port.  So mock something up that will
# pretend to be one and reveal what *would* have been sent over serial
# by logging it.
class DevSerialPort
  def initialize(path)
    self.logger = Rails.logger
  end

  def write(str)
    logger.info("#{self.class}##{__method__} #{str.inspect}")
  end

  def read
    raise NotImplementedError, "No dev stub for read yet"
  end

  def close
    logger.info("#{self.class}##{__method__}")
  end

  private

  attr_accessor :logger
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  attr_accessible :finished_at, :status,
    :number_of_cycles, :pause_between_cycles, :total_quantity,
    :worker
end

app/models/doser.rb
# Administer a dose
class Doser
  def initialize(klass, params, pump, logger)
    @params = params
    @pump = pump
    @dose_class = klass
    @logger = logger
  end

  def run
    save_dose
    do_dosing
  end

  def cancel
    @dose = dose_class.find(params[:id].to_s)
    dose.update_attributes!(finished_at: Time.now, status: :cancelled)
    @@thread.kill
    pump.off
  end

  def start
    save_dose
    @@thread = Thread.new do
      do_dosing
    end
  end

  private

  attr_reader :params, :pump, :dose, :dose_class, :logger

  def save_dose
    @dose = dose_class.create!(sanitize_params)
  end

  def sanitize_params
    pairs = param_types.map do |key, meth|
      [key, params[key].send(meth)]
    end
    Hash[pairs]
  end

  def param_types
    {
      total_quantity: :to_f,
      number_of_cycles: :to_i,
      pause_between_cycles: :to_f,
    }
  end

  def do_dosing
    do_cycles
    record_completion
  # We must catch exceptions when running in separate thread
  rescue Exception => e
    handle_error(e)
    raise
  end

  def do_cycles
    quantity = dose.total_quantity
    cycles = dose.number_of_cycles
    pause = dose.pause_between_cycles

    cycles.times do |i|
      pump.dose(quantity / cycles)
      sleep(pause) if i < cycles - 1 # skip last sleep
    end
  end

  def record_completion
    dose.update_attributes!(finished_at: Time.now, status: :completed)
  end

  def handle_error(e)
    logger.error "Exception while dosing: #{e.message}"
    logger.error "#{e.class}: #{e.message}\n  "+e.backtrace.join("\n  ")
    dose.update_attributes!(finished_at: Time.now, status: :failed)
  end
end

app/models/pump.rb
class Pump
  def initialize(hardware_config)
    serial_config = hardware_config.serial_port
    serial_class = Object.const_get(serial_config.class_name)
    @serial = serial_class.new(serial_config.path)
  end

  def on
    trigger_on
    @serial.close
  end

  def off
    trigger_off
    @serial.close
  end

  def dose(seconds)
    trigger_on
    sleep(seconds)
    trigger_off
  end

private

  def trigger_on
    @serial.write("y")
  end

  def trigger_off
    @serial.write("n")
  end
end

app/models/reading.rb
class Reading < ActiveRecord::Base
  attr_accessible :measured_at, :sensor, :value
  belongs_to :sensor
  validates :measured_at, :sensor, :value, presence: true
  validates :value, numericality: true
  validates :measured_at, uniqueness: { scope: :sensor_id }
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :name, :unit
  has_many :readings
  validates :name, :unit, presence: true
  validates :name, uniqueness: true
end

app/models/simple_serial_port.rb
# Simple wrapper for SerialPort
#
# The SerialPort interface is too broad; I want something narrower
# for which I can provide a good stub in development environments where
# the serial port is not connected to an Arduino.  See SimpleDevSerialPort.
class SimpleSerialPort
  def initialize(path)
    self.serial_port = SerialPort.new(path,
                                      baud=9600, data_bits=8,
                                      stop_bits=1, parity=SerialPort::NONE)
  end

  def write(str)
    serial_port.write(str)
    nil
  end

  def close
    serial_port.close
    nil
  end

  private

  attr_accessor :serial_port
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feeder_controller.rb
class FeederController < ApplicationController
  def index
    @doses = Dose.order("id DESC")
  end

  def feed
    pump.on
    redirect_to index_url_opts, notice: "Fed!"
  end

  def starve
    pump.off
    redirect_to index_url_opts, notice: "Starved :("
  end

  def dose
    Doser.new(Dose, params, pump, logger).start
    redirect_to index_url_opts, notice: "Dosing..."
  end

  def cancel
    Doser.new(Dose, params, pump, logger).cancel
    redirect_to index_url_opts, notice: "Cancelled dose."
  end

  private

  def pump
    Pump.new(Rails.configuration.hardware)
  end

  def index_url_opts
    { action: :index }
  end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sensors }
    end
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/new
  # GET /sensors/new.json
  def new
    @sensor = Sensor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/1/edit
  def edit
    @sensor = Sensor.find(params[:id])
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(params[:sensor])

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render json: @sensor, status: :created, location: @sensor }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sensors/1
  # PUT /sensors/1.json
  def update
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      if @sensor.update_attributes(params[:sensor])
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy

    respond_to do |format|
      format.html { redirect_to sensors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_item(link_text, controller)
    class_opts = {}
    if controller.to_s == controller_name.to_s
      class_opts[:class] = "active"
    end
    return content_tag(:li, class_opts) do
      link_to link_text, url_for(:controller => controller)
    end
  end
end

app/views/feeder/index.html.slim
.page-header
  h1 Feed Me

.form-horizontal: .control-group
  .controls
    .btn-group
        = form_tag feed_path, :style => "display: inline", :class => "btn" do
          = submit_tag "Feed", :class => "btn btn-link"
        = form_tag starve_path, :style => "display: inline", :class => "btn" do
          = submit_tag "Starve", :class => "btn btn-link"

= form_tag dose_path, :class => "form-horizontal" do |f|
  .control-group
    .control-label = label_tag :total_quantity
    .controls = text_field_tag :total_quantity
  .control-group
    .control-label = label_tag :number_of_cycles
    .controls = text_field_tag :number_of_cycles
  .control-group
    .control-label = label_tag :pause_between_cycles
    .controls = text_field_tag :pause_between_cycles
  .control-group
    .controls = submit_tag "Dose", :class => "btn btn-primary"

h2 Dose History

table.table.table-bordered.table-striped
  thead
    tr
      th Total Quantity
      th Number of Cycles
      th Pause Between Cycles
      th Status
      th Finished

  tbody
    - @doses.each do |dose|
      tr
        td = dose.total_quantity
        td = dose.number_of_cycles
        td = dose.pause_between_cycles
        td
          = dose.status.try(:humanize)
          - if dose.status.blank?
            = "Started - "
            = link_to("cancel", cancel_dose_path(dose), :method => :post)
        td = dose.finished_at

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name}"
      a.close data-dismiss="alert" href="#" ×
      = msg

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    title Sensa
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    /! Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      script src="//html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    div.navbar.navbar-top
      div.navbar-inner
        div.container
          a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Sensa BioBot", "/", :class => "brand"
          div.nav-collapse
            ul.nav
              = nav_item("Sensors", :sensors)
              = nav_item("Feeder", :feeder)
              li: a href="#about" About
    div.container
      = render "layouts/messages"
      = yield

      hr
      footer
        p.pull-right: a href="terms" Terms of Service
        p &copy; Sensa Bio 2012

app/views/sensors/_chart.html.erb
<div id='chart'>
  <svg style='height:500px'> </svg>
</div>
<script type="text/javascript">
  var data = [
    { "key": <%=raw "#{@sensor.name} (#{@sensor.unit})".to_json %>,
      "values":
      <%=raw @sensor.readings.map{|r|
        [r.measured_at.to_i*1_000, r.value.to_f]
      }.to_json %>
    }
  ];
  nv.addGraph(function() {
    var chart = nv.models.lineChart()
                  .x(function(d) { return d[0] })
                  // adjusting, 100% is 1.00, not 100 as it is in the data
                  .y(function(d) { return d[1]/100 })
                  .color(d3.scale.category10().range());

     chart.xAxis
        .tickFormat(function(d) {
            return d3.time.format('%a %I:%M:%S %p')(new Date(d))
          });

    chart.yAxis
        .tickFormat(d3.format(',.3%'));

    d3.select('#chart svg')
        .datum(data)
      .transition().duration(500)
        .call(chart);

    //TODO: Figure out a good way to do this automatically
    nv.utils.windowResize(chart.update);

    return chart;
  });
</script>

app/views/sensors/_form.html.slim
= form_for(@sensor, :html => { :class => "form-horizontal" }) do |f|
  - if @sensor.errors.any?
    .alert.alert-error
      .close data-dismiss="alert" href="#" ×
      h2.alert-heading
        = pluralize(@sensor.errors.count, "error")
        |  prohibited this sensor from being saved:

      ul
        - @sensor.errors.full_messages.each do |msg|
          li = msg

  .control-group
    .control-label = f.label :name
    .controls = f.text_field :name
  .control-group
    .control-label = f.label :unit
    .controls = f.text_field :unit
  .control-group
    .controls.actions
      .btn-group
        = f.submit :class => 'btn btn-primary'
        = content_for :actions
        = link_to 'List', sensors_path, :class => 'btn'
      .btn-group
        = content_for :dangerous_actions

app/views/sensors/edit.html.slim
.page-header
  h1 Editing sensor

- content_for :actions do
  = link_to 'Show', @sensor, :class => 'btn'
- content_for :dangerous_actions do
  = link_to 'Destroy', @sensor, class: 'btn btn-danger',
      method: :delete,
      data: { confirm: 'Delete this sensor and all its readings?' }

= render 'form'

app/views/sensors/index.html.slim
.page-header
  h1 Listing sensors

table.table.table-bordered.table-striped
  thead
    tr
      th Name
      th Value
      th Trend

  tbody
    - @sensors.each do |sensor|
      tr
        td = link_to sensor.name, sensor
        td
          - last_two = sensor.readings. \
              order("measured_at desc").limit(2).reverse
          = number_with_precision last_two.last.value
          = " " + sensor.unit
        td
          - if last_two.length == 2
            =raw last_two.first.value < last_two.last.value ? "&uarr;" : "&darr;"
            = " " + number_with_precision((last_two.first.value - last_two.last.value).abs)

= link_to 'New Sensor', new_sensor_path, :class => "btn"

app/views/sensors/new.html.slim
.page-header
  h1 New sensor

= render 'form'

app/views/sensors/show.html.slim
.page-header
  h1
    = @sensor.name
    |  (#{@sensor.unit})

= stylesheet_link_tag "http://nvd3.org/src/nv.d3.css"
= javascript_include_tag "http://d3js.org/d3.v3.min.js", charset: "utf-8"
= javascript_include_tag "http://nvd3.org/nv.d3.js"

= render 'chart'

.btn-group
  = link_to "Edit", edit_sensor_path(@sensor), :class => "btn"
  = link_to "List", sensors_path, :class => "btn"